#!/usr/bin/env python

import os

from app import app as application


application.config['DATABASE'] = os.path.join(os.environ['OPENSHIFT_DATA_DIR'], 'db.sqlite')

logfile_path = os.path.join(os.environ['OPENSHIFT_LOG_DIR'], 'persons.log')
application.add_file_logger(logfile_path)
