#!/usr/bin/env python

import os

import app


application = app.app

application.config['DATABASE'] = os.path.join(os.environ['OPENSHIFT_DATA_DIR'], 'db.sqlite')

logfile_path = os.path.join(os.environ['OPENSHIFT_LOG_DIR'], 'persons.log')
app.add_file_logger(logfile_path)
